import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";

const cairo = Cairo({ subsets: ["arabic", "latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html dir="rtl" lang="ar">
			<body
				className={cn(
					"min-h-screen bg-background antialiased",
					cairo.className,
				)}
			>
				{children}
			</body>
		</html>
	);
}
